### PR TITLE
readme update

### PR DESCRIPTION
**Pull request by omnikron**

### CODE REVIEW

**Comment by punchagan** [comment]
Thanks! :D

**Comment by punchagan** [comment]
Merged, manually.

**Comment by omnikron** [comment]
I wonder why it didn't work automatically?  I never had a merge conflict on a readme before :P 

anyway, thanks for your work on this, it's a fantastic tool (that's how this issue came about - I show it to everybody!)

**Comment by punchagan** [comment]
I accidentally, clicked the wrong button, so I figured it would be easier to do it manually, to just get the commit from your repository and push here.  Also, it avoids having another 'merge' commit for a simple change in readme.

**Comment by omnikron** [comment]
That is a fair point, I would hate to muddy your repo history.  Cheers!

**Pull request merged**
